# -*- coding: utf-8 -*-
"""
Django settings for recalbox-manager project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.join(BASE_DIR, 'project')

SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(_0!&^^xekahfp=s5(9+^wlq6gvn6z90%i*p+wn^4ir+mvl4lx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    
    'autobreadcrumbs',
    
    'project.manager_frontend',
    
    'debug_toolbar',
    
    #'ajaxuploader',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project.utils.context_processors.site_metas',
                'autobreadcrumbs.context_processors.AutoBreadcrumbsContext',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = None

USE_I18N = False

USE_L10N = True

USE_TZ = False


# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/example.com/media/"
MEDIA_ROOT = os.path.join(PROJECT_DIR, 'media')

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://example.com/media/", "http://media.example.com/"
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(PROJECT_DIR, "webapp_statics"),
)

# For Django messages framework, we could use this settings to avoid database requests
#MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

# For Django Debug Toolbar
INTERNAL_IPS = ('192.168.0.112',)

#
# Recalbox needed paths
#

# Path to directory that contains bios file
RECALBOX_BIOS_PATH = "/recalbox/share/bios"
# Path to directory that contains system roms directories
RECALBOX_ROMS_PATH = '/recalbox/share/roms'
# Path to the Recalbox configuration file
RECALBOX_CONF_PATH = '/recalbox/share/system/recalbox.conf'
# Path to the Recalbox configuration backup file
RECALBOX_CONF_BACKUP_PATH = '/recalbox/share/system/recalbox.old.conf'
# Path to the Recalbox logs file
RECALBOX_LOGFILE_PATH = "/recalbox.log"

# Default empty entry for a system unknowed from Manifest
RECALBOX_SYSTEM_DEFAULT = {
    'name': 'Unknow',
    'extensions': [],
    'download_links': [],
    'bios': [],
}

# Recalbox manifest about system roms and bios
# Will soon be parsed from Manifest XML file
RECALBOX_MANIFEST = {
    'atari2600': {
        'name': 'Atari 2600',
        'extensions': ['a26'],
        'download_links': [
            'http://www.planetemu.net/roms/atari-2600',
        ],
    },
    'atari7800': {
        'name': 'Atari 7800',
        'extensions': ['a78', 'bin'],
        'download_links': [
            'http://www.planetemu.net/roms/atari-7800',
        ],
        'bios': [
            ('0763f1ffb006ddbe32e52d497ee848ae', '7800 BIOS (U).rom'),
        ],
    },
    'fba': {
        'name': 'FBA',
        'extensions': ['fba', 'zip'],
        'download_links': [],
    },
    'fba_libretro': {
        'name': 'FBA Libretro',
        'extensions': ['fba', 'zip'],
        'download_links': [],
    },
    'fds': {
        'name': 'Nintendo Family Computer Disk System',
        'extensions': ['fds'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-famicom-disk-system',
        ],
        'bios': [
            ('ca30b50f880eb660a320674ed365ef7a', 'disksys.rom'),
        ],
    },
    'gamegear': {
        'name': 'Game Gear',
        'extensions': ['gg'],
        'download_links': [
            'http://www.planetemu.net/roms/sega-game-gear',
        ],
    },
    'gb': {
        'name': 'Game Boy',
        'extensions': ['gb'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-game-boy',
        ],
    },
    'gba': {
        'name': 'Game Boy Advance',
        'extensions': ['gba'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-game-boy-advance',
        ],
        'bios': [
            ('a860e8c0b6d573d191e4ec7db1b1e4f6', 'gba_bios.bin'),
        ],
    },
    'gbc': {
        'name': 'Game Boy Color',
        'extensions': ['gb', 'gbc'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-game-boy',
            'http://www.planetemu.net/roms/nintendo-game-boy-color',
        ],
    },
    'gw': {
        'name': u'Game & Watch',
        'extensions': ['mgw'],
        'download_links': [
            'http://bot.libretro.com/assets/cores/gw/',
        ],
    },
    'lutro': {
        'name': 'LUA games',
        'extensions': ['lua'],
        'download_links': [
            'https://github.com/libretro/lutro-platformer',
            'https://github.com/libretro/lutro-game-of-life',
            'https://github.com/libretro/lutro-snake',
            'https://github.com/libretro/lutro-tetris',
            'https://github.com/libretro/lutro-iyfct',
            'https://github.com/libretro/lutro-pong',
        ],
    },
    'lynx': {
        'name': 'Lynx',
        'extensions': ['lnx'],
        'download_links': [
            'http://www.planetemu.net/roms/atari-lynx',
        ],
        'bios': [
            ('fcd403db69f54290b51035d82f835e7b', 'lynxboot.img'),
        ],
    },
    'mame': {
        'name': 'Mame',
        'extensions': ['zip'],
        'download_links': [
            'https://www.google.fr/webhp?ie=UTF-8#safe=off&q=mame4all%200.37b5%20complete%20romset%202270',
        ],
    },
    'mastersystem': {
        'name': 'Sega Master System',
        'extensions': ['sms'],
        'download_links': [
            'http://www.planetemu.net/roms/sega-master-system',
        ],
    },
    'megadrive': {
        'name': 'Megadrive',
        'extensions': ['gen', 'md', 'smd', 'bin'],
        'download_links': [
            'http://www.planetemu.net/roms/sega-mega-drive',
        ],
    },
    'msx': {
        'name': 'MSX',
        'extensions': ['mx1', 'mx2'],
        'download_links': [
            'http://www.planetemu.net/roms/goodmsx1',
            'http://www.planetemu.net/roms/goodmsx2',
        ],
        'bios': [
            ('d6dedca1112ddfda94cc9b2e426b818b', 'CARTS.SHA'),
            ('85b38e4128bbc300e675f55b278683a8', 'CYRILLIC.FNT'),
            ('80dcd1ad1a4cf65d64b7ba10504e8190', 'DISK.ROM'),
            ('af8537262df8df267072f359399a7635', 'FMPAC16.ROM'),
            ('6f69cc8b5ed761b03afd78000dfb0e19', 'FMPAC.ROM'),
            ('c83e50e9f33b8dd893c414691822740d', 'ITALIC.FNT'),
            ('febe8782b466d7c3b16de6d104826b34', 'KANJI.ROM'),
            ('2183c2aff17cf4297bdb496de78c2e8a', 'MSX2EXT.ROM'),
            ('7c8243c71d8f143b2531f01afa6a05dc', 'MSX2PEXT.ROM'),
            ('6d8c0ca64e726c82a4b726e9b01cdf1e', 'MSX2P.ROM'),
            ('ec3a01c91f24fbddcbcab0ad301bc9ef', 'MSX2.ROM'),
            ('6418d091cd6907bbcf940324339e43bb', 'MSXDOS2.ROM'),
            ('aa95aea2563cd5ec0a0919b44cc17d47', 'MSX.ROM'),
            ('403cdea1cbd2bb24fae506941f8f655e', 'PAINTER.ROM'),
            ('279efd1eae0d358eecd4edc7d9adedf3', 'RS232.ROM'),
        ],
    },
    'n64': {
        'name': 'Nintendo64',
        'extensions': ['n64', 'v64', 'z64'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-nintendo-64',
        ],
    },
    'neogeo': {
        'name': 'NeoGeo',
        'extensions': ['zip'],
        'download_links': [
            'http://www.gametronik.com/site/AffichListingAll/neogeo/',
        ],
    },
    'nes': {
        'name': 'Nintendo Entertainment System',
        'extensions': ['nes', 'zip'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-nes',
        ],
    },
    'ngp': {
        'name': 'NeoGeo Pocket',
        'extensions': ['ngp', 'ngc'],
        'download_links': [
            'http://www.planetemu.net/roms/snk-neo-geo-pocket',
            'http://www.planetemu.net/roms/snk-neo-geo-pocket-color',
        ],
    },
    'pcengine': {
        'name': 'PC Engine',
        'extensions': ['pce', 'cue', 'ccd', 'sgx'],
        'download_links': [
            'http://www.planetemu.net/roms/nec-pc-engine',
            'http://www.mondemul.net/zisos.php?genre=liste&type=pcecd',
        ],
        'bios': [
            ('ff1a674273fe3540ccef576376407d1d', 'syscard3.pce'),
        ],
    },
    'prboom': {
        'name': 'PRBoom',
        'extensions': ['wad'],
        'download_links': [],
    },
    'psx': {
        'name': 'PSX',
        'extensions': ['img', 'bin', 'iso'],
        'download_links': [
            'http://www.mondemul.net/machine.php?type=psx',
        ],
        'bios': [
            ('924e392ed05558ffdb115408c263dccf', 'SCPH1001.BIN'),
        ],
    },
    'scummvm': {
        'name': 'ScummVM',
        'extensions': None,
        'download_links': [
            'a26',
        ],
    },
    'sega32x': {
        'name': 'Sega 32x',
        'extensions': ['32x', 'smd', 'bin'],
        'download_links': [
            'http://www.planetemu.net/roms/sega-32x',
        ],
        'bios': [
            ('6a5433f6a132a2b683635819a6dcf085', '32X_G_BIOS.BIN'),
            ('f88354ec482be09aeccd76a97bb75868', '32X_M_BIOS.BIN'),
            ('7f041b6a55cd7423a6c08a219335269e', '32X_S_BIOS.BIN'),
        ],
    },
    'segacd': {
        'name': 'Sega CD',
        'extensions': ['cue'],
        'download_links': [
            'http://www.planetemu.net/roms/sega-mega-cd-and-sega-cd-games',
        ],
        'bios': [
            ('854b9150240a198070150e4566ae1290', 'us_scd2_9306.bin'),
            ('d8b8b720dea6c6ba25c309ed633930f4', 'eu_mcd2_9306.bin'),
            ('bdeb4c47da613946d422d97d98b21cda', 'jp_mcd1_9112.bin'),
        ],
    },
    'sg1000': {
        'name': 'SG1000',
        'extensions': ['sg'],
        'download_links': [
            'http://www.planetemu.net/roms/sega-sg-1000',
        ],
    },
    'snes': {
        'name': 'Super Nintendo',
        'extensions': ['sfc', 'smc'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-super-nes',
        ],
    },
    'vectrex': {
        'name': 'Vectrex',
        'extensions': ['vec'],
        'download_links': [
            'http://www.gametronik.com/site/AffichListingAll/vectrex/',
        ],
    },
    'virtualboy': {
        'name': 'Nintendo Virtual Boy',
        'extensions': ['vb'],
        'download_links': [
            'http://www.planetemu.net/roms/nintendo-virtual-boy',
        ],
    },
    'wswan': {
        'name': 'Wonder Swan',
        'extensions': ['ws', 'wsc'],
        'download_links': [
            'http://www.planetemu.net/roms/bandai-wonderswan',
            'http://www.planetemu.net/roms/bandai-wonderswan-color',
        ],
    },
}
